# A list of Warp Route token configs
# These configs will be merged with the warp routes in the configured registry
# The input here is typically the output of the Hyperlane CLI warp deploy command
---
tokens:
  - chainName: devneta
    standard: EvmHypCollateral
    name: ABBB
    symbol: ABBB
    decimals: 18
    totalSupply: 0
    isNft: false
    type: collateral
    token: "0x947da62ca05a1073a8dc19628ea8c304b968416d"
    owner: "0x8943545177806ED17B9F23F0a21ee5948eCaa776"
    mailbox: "0x93b2B592F2e6c16255A4877fAc046b5421915387"
    addressOrDenom: "0x31Cc3402c7D9573c507208D826679F9b4E1ebE86"
    collateralAddressOrDenom: "0x947da62ca05a1073a8dc19628ea8c304b968416d"
    connections:
      - token: ethereum|devnetb|0xf2bD68421A73821368eEefaCB420FFdFa0237c86
  - chainName: devnetb
    standard: EvmHypSynthetic
    name: ABBB
    symbol: ABBB
    decimals: 18
    totalSupply: 0
    isNft: false
    type: synthetic
    owner: "0x8943545177806ED17B9F23F0a21ee5948eCaa776"
    mailbox: "0x700420690932eeB22bCd01fBf537d37BeCa5577C"
    addressOrDenom: "0xf2bD68421A73821368eEefaCB420FFdFa0237c86"
    connections:
      - token: ethereum|devneta|0x31Cc3402c7D9573c507208D826679F9b4E1ebE86

