# A list of Warp Route token configs
# These configs will be merged with the warp routes in the configured registry
# The input here is typically the output of the Hyperlane CLI warp deploy command
---
tokens:
  - chainName: arbitrum
    standard: EvmHypCollateral
    name: USD Coin
    symbol: USDC
    decimals: 6
    totalSupply: 0
    isNft: false
    type: collateral
    token: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
    owner: "0x96E82161fbC0a755704d04Fd9EbF3ee9099488e4"
    mailbox: "0x979Ca5202784112f4738403dBec5D0F3B9daabB9"
    interchainSecurityModule: "0xf1A65648bB0B92be9AcF6f5478036104e1b7B78d"
    addressOrDenom: "0xC9c2c920A51d1a129D3f7724cb5018014E2d2128"
    collateralAddressOrDenom: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
    connections:
      - token: ethereum|endurance|0x70D04b9d98161913e8da475B7ce631b750613ee5
  - chainName: endurance
    standard: EvmHypSynthetic
    name: USDC
    symbol: USDC
    decimals: 6
    totalSupply: 0
    isNft: false
    type: synthetic
    owner: "0x96E82161fbC0a755704d04Fd9EbF3ee9099488e4"
    mailbox: "0xBEF497cd38A86D2Ec90e57695c3F62E16E3bC5bf"
    interchainSecurityModule: "0x60D2AB60bb261C32AD8FF1Beb586b522d9Df316b"
    addressOrDenom: "0x70D04b9d98161913e8da475B7ce631b750613ee5"
    connections:
      - token: ethereum|arbitrum|0xC9c2c920A51d1a129D3f7724cb5018014E2d2128