# A list of Warp Route token configs
# These configs will be merged with the warp routes in the configured registry
# The input here is typically the output of the Hyperlane CLI warp deploy command
---
tokens:
  - chainName: arbitrum
    standard: EvmHypCollateral
    name: USD Coin
    symbol: USDC
    decimals: 6
    totalSupply: 0
    isNft: false
    type: collateral
    token: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
    owner: "0x96E82161fbC0a755704d04Fd9EbF3ee9099488e4"
    mailbox: "0x979Ca5202784112f4738403dBec5D0F3B9daabB9"
    addressOrDenom: "0x579aB9199AFD8e2a800279408b948e14C3124081"
    collateralAddressOrDenom: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
    connections:
      - token: ethereum|endurance|0xce9b3fBe49cA83Ff07BB0b9a09E7363AF8b6FD85
  - chainName: endurance
    standard: EvmHypSynthetic
    name: USDC
    symbol: USDC
    decimals: 6
    totalSupply: 0
    isNft: false
    type: synthetic
    owner: "0x96E82161fbC0a755704d04Fd9EbF3ee9099488e4"
    mailbox: "0xBEF497cd38A86D2Ec90e57695c3F62E16E3bC5bf"
    addressOrDenom: "0xce9b3fBe49cA83Ff07BB0b9a09E7363AF8b6FD85"
    connections:
      - token: ethereum|arbitrum|0x579aB9199AFD8e2a800279408b948e14C3124081